[package]
name = "schema-harvester-test-suite"
publish = false
rust-version = "1.85.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
serde_json = "1.0.139"
schema-harvester = { path = "../core" }
