[package]
name = "schema-harvester-test-suite"
version = "0.0.0"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
serde_json = "1.0.116"
schema-harvester = { path = "../core" }
